categories:
  - title: '🐞 Bugs'
    labels:
      - 'bug'
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '📖 Documentation'
    label:
      - 'documentation'
  - title: '🧰 Maintenance'
    label:
      - 'dependencies'
category-template: "### $TITLE"
template: |
  ## What’s Changed

  $CHANGES

  See also: [Documentation](https://swiftpackageindex.com/pointfreeco/swift-snapshot-testing/main/documentation/snapshottesting)
